version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
