services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    container_name: canterlot_mongodb
    hostname: canterlot_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
      - mongo_search:/data/mongot

  redis:
    image: redis:7.0-alpine
    container_name: canterlot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
    driver: local
  mongo_configdb:
    driver: local
  mongo_search:
    driver: local
  redis_data:
    driver: local
