from collections.abc import Mapping
from datetime import datetime
from typing import Protocol

from beanie import PydanticObjectId

from canterlot.models import (
    AuthProviderName,
    AvatarSchema,
    BookModel,
    CatalogEntryModel,
    ClubModel,
    InviteModel,
    JoinPolicy,
    LinkedProviderSchema,
    MemberRole,
    MemberSchema,
    UserModel,
)
from canterlot.models.book import BookProviderIdentifier, ReadBook, UrlList
from canterlot.models.club import ClubNameStr, ClubSlugStr
from canterlot.models.user import EmailPreferencesSchema, PersonNameStr, UsernameStr
from canterlot.pagination import Page, SortDirection
from canterlot.types import HttpsUrl, ISBN10Str, ISBN13Str, LanguageStr, NormalizedEmailStr


class BookRepository(Protocol):
    async def find_by_external_id(self, external_id: BookProviderIdentifier) -> BookModel | None: ...
    async def find_by_isbn(self, isbn_10: ISBN10Str | None, isbn_13: ISBN13Str | None) -> BookModel | None: ...
    async def find_by_id(self, book_id: PydanticObjectId) -> BookModel | None: ...
    async def find_by_ids(self, book_ids: list[PydanticObjectId]) -> dict[PydanticObjectId, BookModel]: ...
    async def find_id_by_identifier(
        self,
        identifier: BookProviderIdentifier | ISBN10Str,
    ) -> PydanticObjectId | None: ...
    async def add_to_urls(self, book_id: PydanticObjectId, urls: UrlList) -> None: ...
    async def fill_missing_fields(self, book_id: PydanticObjectId, fields: dict[str, object]) -> None: ...
    async def save(self, book: BookModel) -> BookModel: ...


class ClubRepository(Protocol):
    async def find_by_id(self, club_id: PydanticObjectId) -> ClubModel | None: ...
    async def find_club_name_by_id(self, club_id: PydanticObjectId) -> ClubNameStr | None: ...
    async def get_preferred_languages_by_id(self, club_id: PydanticObjectId) -> list[LanguageStr]: ...
    async def find_member_role_by_club_id_and_user_id(
        self,
        club_id: PydanticObjectId,
        user_id: PydanticObjectId,
    ) -> MemberRole | None: ...
    async def find_by_slug(self, slug: ClubSlugStr) -> ClubModel | None: ...
    async def find_id_by_slug(self, slug: ClubSlugStr) -> PydanticObjectId | None: ...
    async def exists_by_club_slug(self, slug: ClubSlugStr) -> bool: ...
    async def exists_by_club_id_and_member_user_id(
        self,
        club_id: PydanticObjectId,
        user_id: PydanticObjectId,
    ) -> bool: ...
    async def exists_by_club_id_and_pending_user_id(
        self,
        club_id: PydanticObjectId,
        user_id: PydanticObjectId,
    ) -> bool: ...
    async def exists_by_club_id_and_catalog_book_id(
        self,
        club_id: PydanticObjectId,
        book_id: PydanticObjectId,
    ) -> bool: ...
    async def find_catalog_entry_by_club_id_and_book_id(
        self,
        club_id: PydanticObjectId,
        book_id: PydanticObjectId,
    ) -> CatalogEntryModel | None: ...
    async def find_catalog_page_by_club_id(
        self,
        club_id: PydanticObjectId,
        page: int,
        limit: int,
        sort_by: str | None = None,
        sort_direction: SortDirection = SortDirection.DESC,
        suggested_by: PydanticObjectId | None = None,
        q: str | None = None,
    ) -> Page[CatalogEntryModel]: ...
    async def is_suggestions_allowed(self, club_id: PydanticObjectId) -> bool: ...
    async def add_member(self, club_id: PydanticObjectId, member: MemberSchema) -> None: ...
    async def remove_member(self, club_id: PydanticObjectId, member_id: PydanticObjectId) -> None: ...
    async def remove_and_ban_member(self, club_id: PydanticObjectId, member_id: PydanticObjectId) -> None: ...
    async def add_to_pending_approvals(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def remove_from_pending_approvals(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def remove_from_banned_users(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def add_to_catalog(self, club_id: PydanticObjectId, entry: CatalogEntryModel) -> None: ...
    async def remove_from_catalog(self, club_id: PydanticObjectId, book_id: PydanticObjectId) -> None: ...
    async def change_member_role(
        self,
        club_id: PydanticObjectId,
        member_id: PydanticObjectId,
        new_role: MemberRole,
    ) -> bool: ...
    async def update_settings(
        self,
        club_id: PydanticObjectId,
        name: ClubNameStr | None = None,
        slug: ClubSlugStr | None = None,
        description: str | None = None,
        join_policy: JoinPolicy | None = None,
        allow_suggestions: bool | None = None,
        preferred_languages: list[LanguageStr] | None = None,
    ) -> bool: ...
    async def transfer_ownership(
        self,
        club_id: PydanticObjectId,
        current_owner_id: PydanticObjectId,
        new_owner_id: PydanticObjectId,
        transferred_at: datetime,
    ) -> bool: ...
    async def reclaim_ownership(
        self,
        club_id: PydanticObjectId,
        former_owner_id: PydanticObjectId,
        current_owner_id: PydanticObjectId,
    ) -> bool: ...
    async def save(self, club: ClubModel) -> ClubModel: ...
    async def delete(self, club_id: PydanticObjectId) -> None: ...


class CacheRepository(Protocol):
    async def find(self, key: str) -> dict[str, str] | None: ...
    async def save(self, key: str, mapping: Mapping[str, str | int | float], expire_seconds: int) -> None: ...
    async def invalidate(self, key: str) -> None: ...


class DatabaseRepository(Protocol):
    async def ping(self) -> bool: ...


class UserRepository(Protocol):
    async def find_by_id(self, user_id: PydanticObjectId) -> UserModel | None: ...
    async def find_username_by_id(self, user_id: PydanticObjectId) -> UsernameStr | None: ...
    async def find_usernames_by_ids(
        self,
        user_ids: list[PydanticObjectId],
    ) -> dict[PydanticObjectId, UsernameStr]: ...
    async def find_by_username(self, username: UsernameStr) -> UserModel | None: ...
    async def find_id_by_username(self, username: UsernameStr) -> PydanticObjectId | None: ...
    async def find_by_email(self, email: NormalizedEmailStr) -> UserModel | None: ...
    async def find_email_preferences_by_email(self, email: NormalizedEmailStr) -> EmailPreferencesSchema | None: ...
    async def find_id_by_linked_provider(
        self,
        provider: AuthProviderName,
        external_id: str,
    ) -> PydanticObjectId | None: ...
    async def is_email_verified_by_id(self, user_id: PydanticObjectId) -> bool: ...
    async def exists_by_username(self, username: UsernameStr) -> bool: ...
    async def exists_by_email(self, email: NormalizedEmailStr) -> bool: ...
    async def save(self, user: UserModel) -> UserModel: ...
    async def save_new_oauth_account(self, user: UserModel) -> UserModel | None: ...
    async def increment_referral_count_by_username(self, username: UsernameStr) -> None: ...
    async def push_read_book_by_id(self, user_id: PydanticObjectId, read_book: ReadBook) -> None: ...
    async def push_refresh_token_by_id(self, user_id: PydanticObjectId, token: str) -> None: ...
    async def pull_refresh_token_by_id(self, user_id: PydanticObjectId, token: str) -> bool: ...
    async def add_linked_provider(self, user_id: PydanticObjectId, entry: LinkedProviderSchema) -> bool: ...
    async def remove_linked_provider(self, user_id: PydanticObjectId, provider: AuthProviderName) -> None: ...
    async def update_linked_provider_picture(
        self,
        user_id: PydanticObjectId,
        provider: AuthProviderName,
        picture_url: HttpsUrl,
    ) -> None: ...
    async def update_profile(
        self,
        user_id: PydanticObjectId,
        name: PersonNameStr | None = None,
        username: UsernameStr | None = None,
    ) -> bool: ...
    async def change_password(
        self,
        user_id: PydanticObjectId,
        hashed_password: str,
        new_refresh_token: str,
    ) -> None: ...
    async def touch_last_seen(self, user_id: PydanticObjectId, now: datetime) -> None: ...
    async def find_avatar_by_id(self, user_id: PydanticObjectId) -> AvatarSchema | None: ...
    async def set_avatar(self, user_id: PydanticObjectId, avatar: AvatarSchema) -> bool: ...
    async def clear_avatar(self, user_id: PydanticObjectId) -> bool: ...
    async def set_generated_avatar_seed(self, user_id: PydanticObjectId, seed: str) -> bool: ...
    async def set_legal_acceptance(
        self,
        user_id: PydanticObjectId,
        terms_version: int,
        terms_at: datetime,
        privacy_version: int,
        privacy_at: datetime,
        profile_completed_at: datetime,
    ) -> bool: ...
    async def set_delivery_failed_by_email(self, email: NormalizedEmailStr, failed: bool) -> bool: ...
    async def apply_global_suppression_by_email(self, email: NormalizedEmailStr, timestamp: datetime) -> bool:
        """Bounces/Permanent Suppressions: Sets delivery_failed=True and blocks ALL categories."""
        ...

    async def apply_spam_suppression_by_email(self, email: NormalizedEmailStr, timestamp: datetime) -> bool:
        """Complaints: Sets delivery_failed=True and blocks everything EXCEPT transactional."""
        ...


class InviteRepository(Protocol):
    async def find_by_id(self, invite_id: str) -> InviteModel | None: ...
    async def find_by_club_id(self, club_id: PydanticObjectId) -> list[InviteModel]: ...
    async def find_one_active_public_by_club_id(self, club_id: PydanticObjectId) -> InviteModel | None: ...
    async def save(self, invite: InviteModel) -> InviteModel: ...
    async def increment_uses_count_by_id(self, invite_id: str) -> None: ...
    async def deactivate_by_id(self, invite_id: str) -> None: ...
    async def deactivate_all_public_by_club_id(self, club_id: PydanticObjectId) -> None: ...
    async def deactivate_all_direct_by_club_id_and_target_email(
        self,
        club_id: PydanticObjectId,
        target_email: NormalizedEmailStr,
    ) -> None: ...


class RateLimiter(Protocol):
    async def evaluate(self, key: str, limit: int, window_seconds: int) -> int | None: ...
