from typing import Protocol

from beanie import PydanticObjectId

from canterlot.models import (
    BookModel,
    CatalogEntryModel,
    ClubModel,
    InviteModel,
    MemberSchema,
    UserModel,
    UserRole,
)
from canterlot.models.book import BookProviderIdentifier, UrlList
from canterlot.models.club import ClubSlugStr
from canterlot.models.user import UsernameStr
from canterlot.utils.format import ISBN10Str, ISBN13Str, LanguageStr, NormalizedEmailStr


class BookRepository(Protocol):
    async def find_by_external_id(self, external_id: BookProviderIdentifier) -> BookModel | None: ...
    async def find_by_isbn(self, isbn_10: ISBN10Str | None, isbn_13: ISBN13Str | None) -> BookModel | None: ...
    async def find_by_id(self, book_id: PydanticObjectId) -> BookModel | None: ...
    async def add_to_urls(self, book_id: PydanticObjectId, urls: UrlList) -> None: ...
    async def fill_missing_fields(self, book_id: PydanticObjectId, fields: dict[str, object]) -> None: ...
    async def save(self, book: BookModel) -> BookModel: ...


class ClubRepository(Protocol):
    async def find_by_id(self, club_id: PydanticObjectId) -> ClubModel | None: ...
    async def get_preferred_languages_by_id(self, club_id: PydanticObjectId) -> list[LanguageStr]: ...
    async def find_member_role_by_club_id_and_user_id(
        self,
        club_id: PydanticObjectId,
        user_id: PydanticObjectId,
    ) -> UserRole | None: ...
    async def find_by_slug(self, slug: ClubSlugStr) -> ClubModel | None: ...
    async def exists_by_club_slug(self, slug: ClubSlugStr) -> bool: ...
    async def exists_by_club_id_and_member_user_id(
        self,
        club_id: PydanticObjectId,
        user_id: PydanticObjectId,
    ) -> bool: ...
    async def exists_by_club_id_and_catalog_book_id(
        self,
        club_id: PydanticObjectId,
        book_id: PydanticObjectId,
    ) -> bool: ...
    async def is_suggestions_allowed(self, club_id: PydanticObjectId) -> bool: ...
    async def add_member(self, club_id: PydanticObjectId, member: MemberSchema) -> None: ...
    async def remove_member(self, club_id: PydanticObjectId, member_id: PydanticObjectId) -> None: ...
    async def add_to_pending_approvals(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def remove_from_pending_approvals(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def add_to_banned_users(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def remove_from_banned_users(self, club_id: PydanticObjectId, user_id: PydanticObjectId) -> None: ...
    async def add_to_catalog(self, club_id: PydanticObjectId, entry: CatalogEntryModel) -> None: ...
    async def remove_from_catalog(self, club_id: PydanticObjectId, book_id: PydanticObjectId) -> None: ...
    async def save(self, club: ClubModel) -> ClubModel: ...


class CacheRepository(Protocol):
    async def find(self, key: str) -> str | None: ...
    async def save(self, key: str, value: str, expire_seconds: int) -> None: ...


class UserRepository(Protocol):
    async def find_by_id(self, user_id: PydanticObjectId) -> UserModel | None: ...
    async def find_username_by_id(self, user_id: PydanticObjectId) -> UsernameStr | None: ...
    async def find_by_username(self, username: UsernameStr) -> UserModel | None: ...
    async def find_by_email(self, email: NormalizedEmailStr) -> UserModel | None: ...
    async def exists_by_username(self, username: UsernameStr) -> bool: ...
    async def exists_by_email(self, email: NormalizedEmailStr) -> bool: ...
    async def save(self, user: UserModel) -> UserModel: ...
    async def increment_referral_count_by_username(self, username: UsernameStr) -> None: ...
    async def push_refresh_token_by_id(self, user_id: PydanticObjectId, token: str) -> None: ...
    async def pull_refresh_token_by_id(self, user_id: PydanticObjectId, token: str) -> None: ...


class InviteRepository(Protocol):
    async def find_by_id(self, invite_id: str) -> InviteModel | None: ...
    async def find_by_club_id(self, club_id: PydanticObjectId) -> list[InviteModel]: ...
    async def find_one_active_public_by_club_id(self, club_id: PydanticObjectId) -> InviteModel | None: ...
    async def save(self, invite: InviteModel) -> InviteModel: ...
    async def increment_uses_count_by_id(self, invite_id: str) -> None: ...
    async def deactivate_by_id(self, invite_id: str) -> None: ...
    async def deactivate_all_public_by_club_id(self, club_id: PydanticObjectId) -> None: ...
    async def dactivate_all_direct_by_club_id_and_target_email(
        self,
        club_id: PydanticObjectId,
        target_email: NormalizedEmailStr,
    ) -> None: ...
